# Generated by Django 5.2.8 on 2025-11-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UXIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('RAGE_CLICK', 'Rage Clicks'), ('DEAD_CLICK', 'Dead Clicks'), ('LOOPING', 'Navigation Loop'), ('FORM_ABANDON', 'Form Abandonment'), ('HIGH_BOUNCE', 'High Bounce Rate')], max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=20)),
                ('description', models.TextField()),
                ('location_url', models.CharField(max_length=500)),
                ('affected_sessions', models.IntegerField()),
                ('impact_score', models.FloatField()),
                ('ai_hypothesis', models.TextField(blank=True, null=True)),
                ('ai_solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.productversion')),
            ],
        ),
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration_sec', models.IntegerField(default=0)),
                ('device_category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('page_views', models.IntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.productversion')),
            ],
        ),
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField(max_length=500)),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('action_type', models.CharField(default='view', max_length=50)),
                ('x_pos', models.IntegerField(null=True)),
                ('y_pos', models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='analytics.visitsession')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_bounces', models.IntegerField(default=0)),
                ('avg_duration', models.FloatField(default=0.0)),
                ('extra_data', models.JSONField(default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.productversion')),
            ],
            options={
                'unique_together': {('version', 'date')},
            },
        ),
    ]
