# Generated by Django 5.2.8 on 2025-11-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("avg_bounce_rate", models.FloatField()),
                ("avg_duration", models.FloatField()),
                ("users_count", models.IntegerField()),
                ("percentage", models.FloatField()),
                ("metrics", models.JSONField(default=dict)),
                ("conversion_rates", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="analytics.productversion",
                    ),
                ),
            ],
        ),
    ]
