# Generated by Django 5.2.8 on 2025-11-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usercohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehit',
            name='browser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='device_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='is_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='referrer_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='screen_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='screen_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='scroll_depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagehit',
            name='time_on_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='browser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='entry_page',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='exit_page',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='is_returning_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='network_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='screen_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='screen_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='screen_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitsession',
            name='traffic_source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uxissue',
            name='issue_type',
            field=models.CharField(choices=[('RAGE_CLICK', 'Rage Clicks'), ('DEAD_CLICK', 'Dead Clicks'), ('LOOPING', 'Navigation Loop'), ('FORM_ABANDON', 'Form Abandonment'), ('HIGH_BOUNCE', 'High Bounce Rate'), ('WANDERING', 'Wandering Users'), ('NAVIGATION_BACK', 'Frequent Back Button Usage'), ('FORM_FIELD_ERRORS', 'Form Input Errors'), ('FUNNEL_DROPOFF', 'Funnel Drop-off Point')], max_length=50),
        ),
        migrations.CreateModel(
            name='PageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('total_views', models.IntegerField()),
                ('unique_visitors', models.IntegerField()),
                ('avg_time_on_page', models.FloatField()),
                ('bounce_rate', models.FloatField()),
                ('exit_rate', models.FloatField()),
                ('avg_scroll_depth', models.FloatField(null=True)),
                ('dominant_cohort', models.CharField(max_length=100, null=True)),
                ('dominant_device', models.CharField(max_length=50, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.productversion')),
            ],
            options={
                'unique_together': {('version', 'url')},
            },
        ),
    ]
