# Generated by Django 5.2.8 on 2025-11-29 00:00

from django.db import migrations, models


def populate_routing_fields(apps, schema_editor):
    UXIssue = apps.get_model('analytics', 'UXIssue')

    role_map = {
        'RAGE_CLICK': ['UX-дизайнер', 'Фронтенд-разработчик'],
        'DEAD_CLICK': ['UX-дизайнер', 'Фронтенд-разработчик'],
        'LOOPING': ['UX-дизайнер', 'Аналитик'],
        'FORM_ABANDON': ['UX-дизайнер', 'Фронтенд-разработчик', 'Аналитик'],
        'HIGH_BOUNCE': ['UX-дизайнер', 'Аналитик'],
    }

    priority_map = {
        'CRITICAL': 'P0',
        'WARNING': 'P1',
        'INFO': 'P2',
    }

    updates = []
    for issue in UXIssue.objects.all():
        changed = False
        if not issue.detected_version_name:
            issue.detected_version_name = issue.version.name if issue.version_id else ""
            changed = True
        if not issue.recommended_specialists:
            issue.recommended_specialists = role_map.get(issue.issue_type, ['Аналитик'])
            changed = True
        if not issue.priority:
            issue.priority = priority_map.get(issue.severity, 'P2')
            changed = True
        if not issue.trend:
            issue.trend = 'new'
            changed = True
        if changed:
            updates.append(issue)

    if updates:
        UXIssue.objects.bulk_update(
            updates,
            ['detected_version_name', 'recommended_specialists', 'priority', 'trend']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usercohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='uxissue',
            name='detected_version_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uxissue',
            name='priority',
            field=models.CharField(default='P2', max_length=20),
        ),
        migrations.AddField(
            model_name='uxissue',
            name='recommended_specialists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='uxissue',
            name='trend',
            field=models.CharField(default='new', max_length=30),
        ),
        migrations.RunPython(populate_routing_fields, migrations.RunPython.noop),
    ]
