# Generated by Django 5.2.8 on 2025-11-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_pagehit_browser_pagehit_device_category_and_more'),
        ('analytics', '0003_uxissue_routing'),
    ]

    operations = []
