# Generated by Django 5.2.8 on 2025-11-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('require_sequence', models.BooleanField(default=True, help_text='Требовать последовательность шагов')),
                ('allow_skip_steps', models.BooleanField(default=False, help_text='Разрешить пропуск шагов')),
                ('is_preset', models.BooleanField(default=False, help_text='Предустановленная воронка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunnelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_json', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_duration_sec', models.FloatField(blank=True, null=True)),
                ('includes_cohorts', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usercohort',
            name='member_client_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='uxissue',
            name='issue_type',
            field=models.CharField(choices=[('RAGE_CLICK', 'Rage Clicks'), ('DEAD_CLICK', 'Dead Clicks'), ('LOOPING', 'Navigation Loop'), ('FORM_ABANDON', 'Form Abandonment'), ('HIGH_BOUNCE', 'High Bounce Rate'), ('WANDERING', 'Wandering Users'), ('NAVIGATION_BACK', 'Frequent Back Button Usage'), ('FORM_FIELD_ERRORS', 'Form Input Errors'), ('FUNNEL_DROPOFF', 'Funnel Drop-off Point'), ('SCAN_AND_DROP', 'Scan And Drop'), ('SEARCH_FAIL', 'Search Fail')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='usercohort',
            index=models.Index(fields=['version', 'name'], name='analytics_u_version_ff723e_idx'),
        ),
        migrations.AddField(
            model_name='conversionfunnel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='analytics.productversion'),
        ),
        migrations.AddField(
            model_name='funnelmetrics',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_cache', to='analytics.conversionfunnel'),
        ),
        migrations.AddField(
            model_name='funnelmetrics',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.productversion'),
        ),
        migrations.AlterUniqueTogether(
            name='conversionfunnel',
            unique_together={('version', 'name')},
        ),
        migrations.AddIndex(
            model_name='funnelmetrics',
            index=models.Index(fields=['funnel', 'version'], name='analytics_f_funnel__747174_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funnelmetrics',
            unique_together={('funnel', 'version', 'includes_cohorts')},
        ),
    ]
