# Generated by Django 5.2.8 on 2025-11-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_conversionfunnel_funnelmetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsession',
            name='goals_id',
            field=models.JSONField(blank=True, default=list, help_text='Список ID целей, достигнутых в этой сессии', null=True),
        ),
    ]
